### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sherifelsabbagh** [SeonghwanSeo/OpenPharmaco#2]
Hi..

I installed the package and everything was fine until I tried to open it ..

A loading screen appears and then nothing happens. nothing opened.

my laptop is MacBook Air M1 2020

**Comment by SeonghwanSeo** [comment]
You can check the import time to see what the problem is.
```bash
python
> import torch
```

After the torch is imported, stop Python with Cmd+D and run OpenPharmaco. If the importing time was a problem, you can get a downloading pop-up window soon.

**Comment by sherifelsabbagh** [comment]
nothing changed..
downloading the library was fine. everything is fine until I try to open it. 
The screen appears and then disappears quickly

**Comment by sherifelsabbagh** [comment]
anyway thank you ..may be sth wrong with my laptop

**Comment by sherifelsabbagh** [comment]
I solved the problem..

it seems I need to install numpy and pymol by myself

**Comment by SeonghwanSeo** [comment]
@sherifelsabbagh oh, I found that the new version (v2.0.0) of numpy is released recently, and it conflicts to PyTorch.

Glad you were able to resolve it.

**Comment by sherifelsabbagh** [comment]
can I ask another question 

<img width="550" alt="Picture 1" src="https://github.com/SeonghwanSeo/OpenPharmaco/assets/60114574/440132b2-d84d-4adf-a529-1a2f4e8c2836">


This spheres correspond to hydrophobic feature.. however I see that they are not aligned with any atom in the ligand.. 
You get my point ? 

I mean, these spheres should be located on one the ligand atoms which would form Hydrophobic interaction right ?
